In [1]:
from huggingface_hub import from_pretrained_keras

In [2]:
model = from_pretrained_keras("/Users/kuba/PJATK/magisterka/a2d2_semantic_segmentation/trained_models/keras_test_unet", local_files_only=True)

config.json not found in /Users/kuba/PJATK/magisterka/a2d2_semantic_segmentation/trained_models/keras_test_unet


In [3]:
import os
os.chdir('..') 

In [4]:
import numpy as np
from src.data.read_data import SAMPLE_IMAGE, SAMPLE_LABEL

In [5]:
image = np.expand_dims(SAMPLE_IMAGE, axis=0)

In [7]:
predictions = model.predict(image)

In [16]:
import evaluate
import json
from PIL import ImageColor
from src.preprocessors.label import label_to_categorical

In [17]:
with open("./data/class_list.json") as f:
    class_colors_mapping_hex = json.load(f)
class_colors_mapping_rgb = {}
for color, label in class_colors_mapping_hex.items():
    class_colors_mapping_rgb[label] = ImageColor.getcolor(color, "RGB")
cat = label_to_categorical(SAMPLE_LABEL, class_colors_mapping_rgb)

In [24]:
model.evaluate(x=image, y=cat)

1/1 [==============================] - 1s 911ms/step - loss: 9.9467 - accuracy: 0.2408


[9.946676254272461, 0.24083885550498962]

In [27]:
acc = evaluate.load("accuracy")
acc.compute(predictions = predictions, references = cat)

ValueError: Predictions and/or references don't match the expected format.
Expected format: {'predictions': Value(dtype='int32', id=None), 'references': Value(dtype='int32', id=None)},
Input predictions: [[[[1.00000000e+00 3.05577064e-10 9.99963880e-01 ... 5.61649621e-30
    2.29371488e-02 6.60100028e-32]
   [1.00000000e+00 3.45687169e-15 2.38377467e-14 ... 5.15065794e-14
    9.77401942e-06 5.09974509e-26]
   [1.00000000e+00 3.43490809e-29 6.40048182e-14 ... 4.03244668e-33
    1.00000000e+00 0.00000000e+00]
   ...
   [1.00000000e+00 1.15272304e-32 1.02107342e-31 ... 1.00000000e+00
    1.23553063e-18 1.00000000e+00]
   [1.00000000e+00 1.66840867e-32 1.66772780e-17 ... 2.01339128e-32
    3.31947308e-06 3.27841995e-32]
   [1.00000000e+00 1.92393318e-18 0.00000000e+00 ... 1.00000000e+00
    8.85887697e-10 9.99995649e-01]]

  [[1.00000000e+00 1.12174472e-04 9.99968886e-01 ... 6.78051524e-26
    1.00000000e+00 8.43171708e-29]
   [1.00000000e+00 7.23929964e-19 1.56954028e-30 ... 7.17504144e-01
    1.00000000e+00 3.63584861e-14]
   [1.00000000e+00 1.97855036e-32 0.00000000e+00 ... 7.55876303e-04
    2.50468016e-01 1.00000000e+00]
   ...
   [1.00000000e+00 1.71617553e-26 1.44171196e-19 ... 7.67131805e-01
    1.00000000e+00 1.44660458e-33]
   [1.00000000e+00 1.33874678e-09 8.87642303e-31 ... 9.51693506e-26
    9.99980450e-01 1.00000000e+00]
   [1.00000000e+00 5.15532001e-24 4.97186399e-36 ... 7.12069032e-12
    1.00000000e+00 3.24386358e-03]]

  [[8.23441863e-01 2.05482649e-16 9.99987960e-01 ... 3.58256662e-33
    5.96129894e-03 0.00000000e+00]
   [1.00000000e+00 1.87112695e-23 8.80792450e-37 ... 4.00565767e-28
    1.00000000e+00 2.67771472e-35]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.09623966e-18
    1.00000000e+00 0.00000000e+00]
   ...
   [1.00000000e+00 9.99999404e-01 0.00000000e+00 ... 5.72427031e-33
    9.99629617e-01 1.00000000e+00]
   [1.00000000e+00 8.13321384e-35 0.00000000e+00 ... 1.15769882e-16
    1.00000000e+00 2.46472522e-23]
   [1.00000000e+00 3.56137753e-03 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 9.52131152e-01]]

  ...

  [[1.00000000e+00 0.00000000e+00 3.01124264e-10 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 3.02299552e-35 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   ...
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]]

  [[1.00000000e+00 0.00000000e+00 1.00000000e+00 ... 2.75978633e-20
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 1.00000000e+00 ... 4.76534187e-05
    1.00000000e+00 7.74369961e-36]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.10114955e-12
    1.00000000e+00 9.95906089e-34]
   ...
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 1.00000000e+00 3.39431623e-24 ... 0.00000000e+00
    1.00000000e+00 3.62777164e-14]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]]

  [[1.00000000e+00 8.95129826e-31 1.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 3.18293679e-34
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   ...
   [1.00000000e+00 1.59154515e-32 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]
   [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
    1.00000000e+00 0.00000000e+00]]]],
Input references: [[[[0. 0. 0. ... 1. 0. 0.]
   [0. 0. 0. ... 1. 0. 0.]
   [0. 0. 0. ... 1. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 1. 0. 0.]
   [0. 0. 0. ... 1. 0. 0.]
   [0. 0. 0. ... 1. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 1. 0. 0.]
   [0. 0. 0. ... 1. 0. 0.]
   [0. 0. 0. ... 1. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  ...

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [1. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [1. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]]

In [30]:
predictions[0][0][0]

array([1.00000000e+00, 3.05577064e-10, 9.99963880e-01, 1.00000000e+00,
       1.81710029e-12, 1.53395534e-03, 1.96186193e-13, 2.46602667e-07,
       1.00000000e+00, 3.35960198e-30, 1.49319902e-15, 1.73499856e-07,
       1.38098730e-17, 5.14500565e-24, 1.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 5.19518784e-28, 1.00000000e+00, 1.30114271e-26,
       8.54930341e-01, 0.00000000e+00, 6.73093225e-26, 1.00000000e+00,
       5.61633335e-27, 1.00000000e+00, 9.99514043e-01, 2.98518614e-08,
       1.00000000e+00, 6.32270425e-22, 5.28304796e-11, 2.25448464e-19,
       9.83921051e-01, 6.33336549e-32, 1.95245313e-11, 1.91992910e-08,
       9.99999881e-01, 4.73819579e-30, 1.00000000e+00, 9.98575509e-01,
       1.12292086e-36, 1.39730965e-08, 1.70820668e-19, 1.00000000e+00,
       5.38080931e-04, 7.33137131e-04, 2.66599765e-17, 7.15747046e-06,
       1.24596698e-33, 4.40346788e-13, 5.74539749e-20, 1.00000000e+00,
       5.61649621e-30, 2.29371488e-02, 6.60100028e-32], dtype=float32)

In [31]:
cat[0][0][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0.], dtype=float32)

In [ ]:
# todo predictions to classes (like in first notebook)